format_version: v1.0
type: UniqueComponent
attributes: {id: ethercat_lan9253}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_LAN9253_PLIB}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ethercat_lan9253, value: QSPI}
  - type: Combo
    attributes: {id: DRV_LAN9253_PROTOCOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ethercat_lan9253, value: SQI}
  - type: Combo
    attributes: {id: DRV_LAN9253_SQI_MODE_ACCESS_TYPE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: DRV_LAN9253_TIMER_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ethercat_lan9253, value: TC0}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: LAN9253_SPI_Dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectDependency
    attributes: {id: LAN9253_SQI_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: qspi}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: QSPI_SQI}
  - type: DirectDependency
    attributes: {id: LAN9253_TMR_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tc0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: TC0_TMR}
  - type: DirectCapability
    attributes: {id: drvEthercatLan9253}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: ethercat_apps_config}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: EtherCAT_LANDRV_Dependency}
- type: ElementPosition
  attributes: {x: '213', y: '139', id: ethercat_lan9253}
