format_version: v1.0
type: UniqueComponent
attributes: {id: ethercat_apps_config}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: ETHERCAT_FOE_FILE_NAME_LENGTH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '32'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: EtherCAT_LANDRV_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: ethercat_lan9253}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drvEthercatLan9253}
- type: ElementPosition
  attributes: {x: '359', y: '197', id: ethercat_apps_config}
