configName: samE53_lan9255_evb
folderName: same53_lan9255_evb
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAME53J20A
projectName: ethercat_counter_foe_app
settings:
  PackageFilter: aws_cloud;azure_rtos;bootloader;bsp;core;crypto;csp;ethercat;net;net;net;net;net;net;net;net;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAME53_DFP\3.4.79\atdf\ATSAME53J20A.atdf
